apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: cnu1812/s2b2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: s2b2-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
   - name: s2b2-app
     port: 80
     targetPort: 8080